/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_jni_libshapefile_JNIWrapper */

#ifndef _Included_com_github_jni_libshapefile_JNIWrapper
#define _Included_com_github_jni_libshapefile_JNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_jni_libshapefile_JNIWrapper
 * Method:    JNI_shapefile_lib_version
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_jni_libshapefile_JNIWrapper_JNI_1shapefile_1lib_1version
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
