/***********************************************************************************************
* Copyright ©2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware Inc. ALL RIGHTS RESERVED.  *
*                                  MapAware License v1.0                                       *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION OBTAINING A COPY *
* OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE, DISPLAY, DISTRIBUTE, EXECUTE, AND *
* TRANSMIT THE SOFTWARE, AND TO PREPARE DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD  *
* PARTIES TO WHOM THE SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :           *
*                                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING THE ABOVE LICENSE *
* GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST BE INCLUDED IN ALL COPIES OF THE  *
* SOFTWARE, IN WHOLE OR IN PART, AND ALL DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES  *
* OR DERIVATIVE WORKS ARE SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY  *
* A SOURCE LANGUAGE PROCESSOR.                                                                 *
*                                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS",WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING *
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,TITLE *
* AND NON - INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE   *
* SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,WHETHER IN CONTRACT,TORT OR OTHERWISE, *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
* SOFTWARE.                                                                                    *
***********************************************************************************************/
/**
 * @file unitypes.h
 * @brief 跨平台统一整数类型定义
 *  提供固定宽度的整数类型别名，保证在所有平台上表现一致
 *  适用于 macOS, Linux, Windows, Cygwin, MinGW 等环境
 * @author cheungmine@qq.com
 * @copyright © 2024-2025 mapaware.top All Rights Reserved.
 * @version 0.0.33
 *
 * @since 2025-08-18 15:22:29
 * @date 2025-12-05 02:23:33
 */
#ifndef UNITYPES_H_
#define UNITYPES_H_

#ifdef __cplusplus
extern "C" {
#endif

#include "platforms.h"
#include <inttypes.h>   // printf("%"PRId64, val)
#include <float.h>

/* 64-bit 无符号整数 */
typedef uint64_t ub8;
#define UB8MAX UINT64_MAX  ///< ub8 最大值

/* 64-bit 有符号整数 */
typedef int64_t sb8;
#define SB8MAX INT64_MAX   ///< sb8 最大值

/* 32-bit 无符号整数 */
typedef uint32_t ub4;
#define UB4MAX UINT32_MAX  ///< ub4 最大值

/* 32-bit 有符号整数 */
typedef int32_t sb4;
#define SB4MAX INT32_MAX   ///< sb4 最大值

/* 16-bit 无符号整数 */
typedef uint16_t ub2;
#define UB2MAX UINT16_MAX  ///< ub2 最大值

/* 16-bit 有符号整数 */
typedef int16_t sb2;
#define SB2MAX INT16_MAX   ///< sb2 最大值

/* 8-bit 无符号整数 */
typedef uint8_t ub1;
#define UB1MAX UINT8_MAX   ///< ub1 最大值

/* 8-bit 有符号整数 */
typedef int8_t sb1;
#define SB1MAX INT8_MAX    ///< sb1 最大值

/* 获取 64 位整数的低 32 位（返回 uint64_t，低 32 位有效，高 32 位为 0）*/
#define UINT64_LOW32(x)  ((uint64_t)((x) & UINT64_C(0xFFFFFFFF)))

/* 获取 64 位整数的高 32 位（返回 uint64_t，低 32 位为高 32 位内容，高 32 位为 0）*/
#define UINT64_HIGH32(x)  ((uint64_t)((x) >> 32))

typedef float f32;
typedef double f64;

// 绝对值
#ifndef ABS_VAL
    #define ABS_VAL(v)   ((v) < 0 ? -(v) : (v))
#endif

/**
 * 安全地将指针转换为 int 类型（用于原本就是 int 转换而来的指针）
 * 使用双重转换避免编译器警告：
 * 1. 先将指针转换为 uintptr_t（与指针大小相同的无符号整数类型）
 * 2. 再将 uintptr_t 转换为目标整数类型
 */
#define PtrToInt(p) ((int)(uintptr_t)(p))

/**
 * 安全地将 int 类型转换回指针（用于原本就是指针转换而来的整数）
 * 使用双重转换确保类型安全：
 * 1. 先将整数转换为 uintptr_t
 * 2. 再将 uintptr_t 转换为指针类型
 */
#define IntToPtr(i) ((void*)(uintptr_t)(i))

/**
 * 安全地将指针转换为 int64_t 类型（用于原本就是 int64_t 转换而来的指针）
 * 使用双重转换避免编译器警告
 */
#define PtrToInt64(p) ((int64_t)(uint64_t)(p))

/**
 * 安全地将 int64_t 类型转换回指针（用于原本就是指针转换而来的整数）
 * 使用双重转换确保类型安全
 */
#define Int64ToPtr(i) ((void*)(uint64_t)(i))

/*********************************************************************/
#if defined(__cplusplus)
}
#endif

#endif /* UNITYPES_H_ */
